// Builds the vendored Milkdown bundle into Dblore/Resources/MarkdownEditor/.
// Run with `npm ci && npm run build` from this folder; commit the outputs.
import * as esbuild from 'esbuild'
import { mkdirSync, readdirSync, readFileSync, writeFileSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

const here = dirname(fileURLToPath(import.meta.url))
const outDir = join(here, '../../Dblore/Resources/MarkdownEditor')
mkdirSync(outDir, { recursive: true })

const js = await esbuild.build({
  absWorkingDir: here,
  entryPoints: ['src/main.js'],
  bundle: true,
  format: 'iife',
  minify: true,
  target: ['safari17'],
  metafile: true,
  legalComments: 'none',
  outfile: join(outDir, 'markdown-editor.js'),
})

await esbuild.build({
  absWorkingDir: here,
  entryPoints: ['src/style.css'],
  bundle: true,
  minify: true,
  outfile: join(outDir, 'markdown-editor.css'),
})

// Collect the packages that ended up in the JS bundle (scoped names included).
const MODULES_DIR = 'node_modules/'
const packageDirs = new Set()
for (const input of Object.keys(js.metafile.inputs)) {
  const index = input.lastIndexOf(MODULES_DIR)
  if (index === -1) continue
  const rest = input.slice(index + MODULES_DIR.length).split('/')
  const nameParts = rest[0].startsWith('@') ? rest.slice(0, 2) : rest.slice(0, 1)
  packageDirs.add(input.slice(0, index + MODULES_DIR.length) + nameParts.join('/'))
}

const LICENSE_NAMES = ['license', 'license.md', 'license.txt', 'licence', 'licence.md', 'licence.txt']
const missing = []
const sections = []
for (const dir of [...packageDirs].sort()) {
  const absDir = join(here, dir)
  const pkg = JSON.parse(readFileSync(join(absDir, 'package.json'), 'utf8'))
  const licenseFile = readdirSync(absDir).find((file) => LICENSE_NAMES.includes(file.toLowerCase()))
  if (!licenseFile) {
    missing.push(`${pkg.name}@${pkg.version}`)
    continue
  }
  const text = readFileSync(join(absDir, licenseFile), 'utf8').trim()
  sections.push(`${pkg.name} ${pkg.version}\n${'-'.repeat(72)}\n${text}\n`)
}

if (missing.length > 0) {
  console.error(`Missing license file for: ${missing.join(', ')}`)
  process.exit(1)
}

const header =
  'Third-party licenses for markdown-editor.js (generated by scripts/markdown-editor/build.mjs)\n'
writeFileSync(
  join(outDir, 'markdown-editor-licenses.txt'),
  `${header}\n${sections.join('\n')}`,
)

console.log(`Bundled ${sections.length} packages into ${outDir}`)
