#!/bin/bash
# Clean CLAUDE.md files generated by claude-mem plugin before build
# This prevents "Multiple commands produce" errors in Xcode

# Use SRCROOT if available (Xcode), otherwise use script location
if [ -z "$SRCROOT" ]; then
  SRCROOT="$(cd "$(dirname "$0")/.." && pwd)"
fi

# Clean CLAUDE.md files
find "${SRCROOT}/SQLNotebook" -name "CLAUDE.md" -type f -delete 2>/dev/null || true

exit 0
